In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("synthetic_vitals_dataset.csv")

In [3]:
df.head()

,age,bloodGroup,hasBpHigh,hasBpLow,gender,height,hasDiabetes,weight,heartRate,SpO2,temperature,label
0,89,B-,0,0,Male,167.060594,0,83.055983,91.657786,97.806727,36.652197,normal
1,69,O-,0,0,Female,159.971568,0,89.331103,84.741241,94.501253,36.672688,abnormal
2,22,O-,1,0,Other,180.740165,0,68.505850,47.090314,97.193393,36.981732,abnormal
3,29,O+,0,0,Female,164.609434,1,69.614744,98.309805,96.460380,36.546662,abnormal
4,50,O+,0,0,Male,177.948920,1,63.051033,70.211782,95.781098,37.249586,abnormal

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   age          5000 non-null   int64
 1   bloodGroup   5000 non-null   object
 2   hasBpHigh    5000 non-null   int64
 3   hasBpLow     5000 non-null   int64
 4   gender       5000 non-null   object
 5   height       5000 non-null   float64
 6   hasDiabetes  5000 non-null   int64
 7   weight       5000 non-null   float64
 8   heartRate    5000 non-null   float64
 9   SpO2         5000 non-null   float64
 10  temperature  5000 non-null   float64
 11  label        5000 non-null   object
dtypes: float64(5), int64(4), object(3)
memory usage: 468.9+ KB

In [5]:
df.describe()

,age,hasBpHigh,hasBpLow,height,hasDiabetes,weight,heartRate,SpO2,temperature
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,45.25980,0.497800,0.497800,165.003036,0.494000,70.040823,79.826321,96.974540,36.801965
std,25.91468,0.500045,0.500045,10.011083,0.500014,14.443080,14.977463,1.892436,0.497787
min,1.00000,0.000000,0.000000,140.000000,0.000000,40.000000,30.000000,90.387275,35.146643
25%,23.00000,0.000000,0.000000,158.236587,0.000000,59.896762,69.436156,95.661000,36.472045
50%,45.00000,0.000000,0.000000,165.033027,0.000000,69.639847,80.026341,97.067202,36.797341
75%,68.00000,1.000000,1.000000,171.673215,1.000000,80.015516,90.177030,98.374473,37.141647
max,89.00000,1.000000,1.000000,200.000000,1.000000,120.674139,129.043304,100.000000,38.612233